model_name_or_path: "/root/zindi/models/marian/marian_output/checkpoint-860"
# "models/nllb/nllb_output/checkpoint-108"
# "facebook/nllb-200-distilled-600M"
# 
checkpoint: "checkpoint-700"
image_name: "zindi-image:0.3.0"
file_path: "deployment/docker-compose.yml"
new_model_path: "models/marian/marian_output/"
ct_model_path: "models/marian/marian_output/ct/"

# model_checkpoint="/root/zindi/models/marian/marian_output/"+checkpoint
# model_checkpoint_ct="/root/zindi/models/marian/ct/"+checkpoint
# checkpoint_name = "checkpoint-1700"
# output_dir="models/marian/ct/"+checkpoint_name
# output_dir="/home/rana/Projects/zindi/models/marian/ct/"+checkpoint_name

