model_name_or_path: "Helsinki-NLP/opus-mt-af-fr"
checkpoint: "checkpoint-V2-"
image_name: "zindi-image:0.2.6"
file_path: "deployment/docker-compose.yml"
new_model_path: "models/marian/marian_output/"
ct_model_path: "models/marian/ct/"

# model_checkpoint="/root/zindi/models/marian/marian_output/"+checkpoint
# model_checkpoint_ct="/root/zindi/models/marian/ct/"+checkpoint
# checkpoint_name = "checkpoint-1700"
# output_dir="models/marian/ct/"+checkpoint_name
# output_dir="/home/rana/Projects/zindi/models/marian/ct/"+checkpoint_name

